### ISSUE TITLE
Pip-installed 0.4.0 failing on python3

### ISSUE THREAD

**Issue by fluffy-critter** [Ryuno-Ki/webmention-tools#19]
When I attempt to import webmention-tools via pip in a Python3 project, I get the following error:

```
  File "/Users/fluffy/projects/Pushl/pushl/entries.py", line 7, in <module>
    from webmentiontools.send import WebmentionSend
  File "/Users/fluffy/.local/share/virtualenvs/Pushl-kcLf-ZN8/lib/python3.7/site-packages/webmentiontools/send.py", line 5, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'
```

It looks like the code that's checked in is correctly using `urllib.parse` so I'm guessing that there just hasn't been a py3-compatible release uploaded into PyPI just yet. And it looks like v0.4.0 was indeed released back in May, 2014 -- so, you might want to consider updating this. :)

**Comment by Ryuno-Ki** [comment]
Fixed with https://github.com/Ryuno-Ki/webmention-tools/blob/219e8dfca0c42db93c6b56d5a7b848fef740ad2d/webmentiontools/parser.py#L1 I guess.
