### ISSUE TITLE
Bring back Python 2 compatibility

### ISSUE THREAD

**Issue by snarfed** [Ryuno-Ki/webmention-tools#46]
thank you for working on this so much recently, @Ryuno-Ki! it's great to have a maintainer again.

i noticed that one of your early changes was to remove Python 2 compatibility, in particular by adding httplink as dependency, which is Python 3 only.

sadly i have to keep granary and Bridgy Python 2 compatible for the foreseeable future, at least for a year or two more, due to both existing users and App Engine standard APIs still requiring it. this means i can't use your new package as is, so i'd have to continue using my fork instead.

sorry if this is a surprise. let me know if i can answer any questions!

**Comment by Ryuno-Ki** [comment]
Hi @snarfed,

wow, you know, Python 2 will reach EOL „soon“ (again?).

Before I publish a new version I wanted to go through a few items.
Will look into supporting both versions of Python via an import switch.

That is, looking at what makes httplink Py3 only.

Thanks for bringing this up.

**Comment by Ryuno-Ki** [comment]
@snarfed Could you try, whether https://github.com/Ryuno-Ki/webmention-tools/pull/47 works for you?
https://github.com/Ryuno-Ki/webmention-tools/tree/python27 is the corresponding branch.
If so, I'll fork httplink and point pip to that instead of carrying a file in a vendor directory.
